services:
  
  app:
    image: node:18-alpine
    container_name: todo-app2
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos

  mysql:
    image: mysql:8.0
    container_name: todo-mysql2
    volumes:
      - todo-mysql-data2:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: todos

  nginx-custom:
    image: nginx:latest
    container_name: nginx-rev-proxy2
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

volumes:
  todo-mysql-data2: